categories:
  - name: Interpretability
    short: INT
    color: green
  - name: NMT
    short: NMT
    color: blue
  - name: Meta
    short: MET
    color: orange
  - name: Linguistic Properties
    short: LIN
    color: yellow
  - name: Language Modeling
    short: LMI
    color: pink
  - name: Generation
    short: GEN
    color: red
journals:
  - name: IEEE Transactions on Pattern Analysis and Machine Intelligence
    short: IEEE PAMI
  - name:  Pattern Recognition
    short: PR
  - name: IEEE Transactions on Neural Networks and Learning Systems
    short: IEEE NNLS
  - name: Journal of Machine Learning Research
    short: JMLR
  - name: Artificial Intelligence
    short: AI
  - name: Journal of Artificial Intelligence Research
    short: JAIR
  - name: Computational linguistics (Association for Computational Linguistics)
    short: CL
  - name: Transactions of the Association for Computational Linguistics
    short: TACL
  - name: Italian Journal of Computational Linguistics
    short: IJCoL
conferences:
  - name: Annual Meeting of the Association for Computational Linguistics
    short: ACL
  - name: Empirical Methods in Natural Language Processing
    short: EMNLP
  - name: Computational Natural Language Learning
    short: CoNLL
  - name: Asia-Pacific Chapter of the Association for Computational Linguistics
    short: AACL
  - name: European Chapter of the Association for Computational Linguistics
    short: EACL
  - name: North American Chapter of the Association for Computational Linguistics
    short: NAACL
  - name: Conference on Machine Translation
    short: WMT
  - name: International Conference on Computational Linguistics
    short: COLING
  - name: Language Resources and Evaluation
    short: LREC
  - name: Computer Vision and Pattern Recognition
    short: CVPR
  - name: Neural Information Processing Systems
    short: NeurIPS
  - name: AAAI
    short: AAAI
  - name: International Conference on Machine Learning
    short: ICML
  - name: International Conference on Learning Representations
    short: ICLR
  - name: Building Educational Applications
    short: BEA
  - name: Natural Language Generation, Evaluation and Metrics
    short: GEM
  - name: Representation Learning for NLP
    short: Rep4NLP
  - name: BlackboxNLP
    short: BlackboxNLP
  - name: Fact Extraction and VERification
    short: FEVER
  - name: Neural Generation and Translation
    short: NGT
  - name: Cognitive Modeling and Computational Linguistics
    short: CMCL
  - name: Findings of the Association for Computational Linguistics
    short: Findings
  - name: Nordic Conference on Computational Linguistics
    short: NoDaLiDa